### ISSUE TITLE
Verify that you are the owner of plausible.io on Mastodon

### ISSUE THREAD

**Issue by TheEvilSkeleton** [plausible/website#101]
If you go to `Preferences` > `Appearance`, next to `Profile metadata`, you will notice `Verification`. You can verify and confirm that you are the owner of the website you provide in the `Profile metadata`. It should look like this when done properly (green means verified):

![image](https://user-images.githubusercontent.com/50847364/88229376-a2d30b00-cc3e-11ea-8cb5-35d04c35aab4.png)

**Comment by metmarkosaric** [comment]
Thanks! Added rel="me" to the Mastodon link in our footer now. I assume it will take a bit before Mastodon recognizes it and updates our profile.

**Comment by TheEvilSkeleton** [comment]
It should change almost instantaneously. I'm not sure why it didn't work right now.

**Comment by metmarkosaric** [comment]
Works now after removing the link from Mastodon and then adding it again!

**Comment by TheEvilSkeleton** [comment]
Weird...
