### ISSUE TITLE
Mention plausible in more clear way under "Open source and self-hosted Google Analytics alternatives" section

### ISSUE THREAD

**Issue by emanuelb** [plausible/website#238]
I am sharing this link:
https://plausible.io/blog/google-analytics-alternatives#open-source-and-self-hosted-google-analytics-alternatives
which is this page on github:
https://github.com/plausible/website/blob/fa0286b4692e3a08d4d764863867bc8335c1423d/_posts/2020-04-24-60-best-google-analytics-alternatives-the-complete-list-for-2020.md#open-source-and-self-hosted-google-analytics-alternatives

including the hash to point into "Open source and self-hosted Google Analytics alternatives" section

The text shows:
> These open-source Google Analytics alternatives allow you to download their software, install it and run it from your web server. Some offer premium hosted solutions too.

And then mention some alternatives like Matomo etc... but not word about plausible, maybe add some text like , 
we plausible are also open-source & self-hosted, you can read about us above at:
https://plausible.io/blog/google-analytics-alternatives#plausible-analytics

Also the link at text "open-source Google Analytics alternatives" is point to https://plausible.io/open-source-website-analytics which is article only about Plausible, so the text should be changed...

**Comment by metmarkosaric** [comment]
thank you! i've made some tweaks!
