### ISSUE TITLE
Regarding comparison vs cloudflare web analytics

### ISSUE THREAD

**Issue by Novezeil** [plausible/website#247]
It happens to us that as we are running CF web analytics and plausible side by side and intend to fully replace CF web analytics with plausible, and I've been reading the https://plausible.io/vs-cloudflare-web-analytics#cloudflare-limits-you-to-one-website-only very carefully but noticed few things outdated or in doubt.

First is regarding CF web analytics's site limits - currently per CF (https://developers.cloudflare.com/analytics/web-analytics/getting-started) the soft limit of properties are 10 (instead of 1 mentioned below) and it can be escalated via support relatively easily. I'll skip mentioning what's the upper limit we are getting as due to pro / business / enterprise the cap can be totally different, it's not unlimited but what I would say it's vastly usable for us in terms of SaaS.

https://github.com/plausible/website/blob/57f28fc6c6044e33bfb4c2eda77b21865f318321/_articles/cloudflare-web-analytics-vs-plausible-analytics.md#L79-L81

And this brings into another question regarding the website limit from plausible's on-cloud option, that per pricing page (https://plausible.io/#pricing) there's a rule of thumb website limit of 20 instead of "unlimited" mention below. 
https://github.com/plausible/website/blob/57f28fc6c6044e33bfb4c2eda77b21865f318321/_articles/cloudflare-web-analytics-vs-plausible-analytics.md#L83

Appreciate this may either referring to the on-premise option, or the business model has changed since this article is published, but for us the 20 website limits as part of paid plan regardless monthly PV is an immediate deal breaker on first impression. Again I appreciate this may get escalated either free or with minor charge as long as everything is under fair use, however the current competitiveness on this particular topic vs. CF is now limited.

The last not-so-important update is regarding the data retention period of CF, which is the whole point why we are looking at plausible as a drop-in replacement of all CF web analytics we are running. However I believe CF web analytics's retention period is now much longer than 7 days instead of below.

https://github.com/plausible/website/blob/57f28fc6c6044e33bfb4c2eda77b21865f318321/_articles/cloudflare-web-analytics-vs-plausible-analytics.md#L41 

As CF web analytics are still in beta and there're lots of moving parts, what would be interesting to see is how plausible is going to respond to all new changes being implemented by CF with a review of current business model and strategy to make the product offering more competitive.

**Comment by metmarkosaric** [comment]
thanks for the heads up @Novezeil! this was originally published in January so i need to have another look and update it

**Comment by metmarkosaric** [comment]
i've now updated the site limit section. can also see they added Core Web Vitals so have added a note on that too. 

no official word on the new data retention limit so i have now installed CF web analytics on a site to be able to see what happens so i can update that part. last i checked, they would remove all stats that happened more than 7 days ago

there's no plans to change anything in Plausible in response to this. we keep following [our roadmap](https://github.com/plausible/analytics/projects/1)

we recently made a change when we introduced a sites API that allows you to manage sites programmatically. now the first 20 sites are free while there's an additional charge for all the networks and others with a large number of sites. normally something like sites API is an enterprise feature only but we wanted to keep all the features open to all the plans and didn't want to create an enterprise tier with exclusive features so this is what we came up with

**Comment by metmarkosaric** [comment]
looks like the data retention is now longer than 7 days so i've updated the post. no official word on the actual data retention anywhere. they've also returned the "sampling based on 10%" note to the dashboard so i've included that too with updated stats. thanks again!
