### ISSUE TITLE
Minor mobile layout issue

### ISSUE THREAD

**Issue by qw-in** [plausible/website#281]
![Screenshot_20210920-121458](https://user-images.githubusercontent.com/19194187/134061201-47e9548f-2eb6-4dff-9811-ad3f444b087b.jpg)

- Oneplus 8 Pro
- Firefox

Looking forward to trying out plausible!

**Comment by metmarkosaric** [comment]
thanks for reporting @qw-in! i reported the same issue few days ago [in this thread](https://github.com/plausible/analytics/issues/1272) but yeah here it's probably the best place. have fun exploring Plausible!

**Comment by hirusi** [comment]
Does this look good to you, @metmarkosaric ?

![Screen Shot 2021-09-28 at 11 20 39](https://user-images.githubusercontent.com/3974019/135030730-e591df85-8825-4c0b-8fdc-5d18f5df403c.png)

If so, I'll finish this tomorrow (tablet+desktop adjustments) and open a PR.

**Comment by metmarkosaric** [comment]
yeah, that looks great @hirusi! thanks!
