### ISSUE TITLE
What is the source?

### ISSUE THREAD

**Issue by bencresty** [plausible/website#387]
If there are no sources shown on the left side of the view, while no filters are active, but there are top pages shown on the right side of the view... what are the sources? Shouldn't there be any sources shown on the left side? Or does this mean visitors who came directly to the url without going through google or other source?

**Comment by RobertJoonas** [comment]
Hi @bencresty!

Yes, if there are no sources shown in the Top Sources tab, it means that every visitor came to your site directly (or more generally, Plausible was not able to read any referral source for the visitors).

We don't show the "direct/none" source in the main view of Top Sources. When we were adding the "direct/none" source we asked the community about it and most people said that they're prefer it being away from the main view. Most don't see it as actionable as other sources and also it stands for the majority of traffic for most sites which skews our little comparison we have on the dashboard.

Plausible has full support for UTM tags. If you want the most accurate referrer data, I recommend tagging all the links you share. You can read more about UTM tags here: https://plausible.io/blog/utm-tracking-tags

Hope this helps!

**Comment by bencresty** [comment]
@RobertJoonas  Thanks for clearing this up. Clear now!
