### ISSUE TITLE
Landing page image does not include new metrics

### ISSUE THREAD

**Issue by aanndryyyy** [plausible/website#418]
Something that caught my eye after the latest changes.

Currently:
<img width="961" alt="image" src="https://user-images.githubusercontent.com/1809802/224973249-c4e3fdca-f81f-46b2-94a8-411fca25c69a.png">

Should be:
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/1809802/224973431-51182861-9025-4edc-b0bb-4f28d6df1e03.png">

I would format the new one but I don't have that black window frame.

**Comment by metmarkosaric** [comment]
thanks for the heads up @aanndryyyy! we're getting close to completing comparisons so waiting with a new screenshot to also showcase that feature too!

**Comment by metmarkosaric** [comment]
screenshot has been updated
