### ISSUE TITLE
Question: Do I need consent banners with Plausible?

### ISSUE THREAD

**Issue by ihucos** [plausible/website#53]
Here is an article, that explains pseudonymization vs. anonymization according to the GDPR.
https://piwik.pro/blog/benefits-data-pseudonymization-anonymization-gdpr/

In my understanding, plausible uses pseudonymization, since [there is an user id](https://github.com/plausible/analytics/blob/20ab045b9cd0b6d08e02fc4e4b966e6841976555/lib/plausible_web/controllers/api/external_controller.ex#L52) derived from a fingerprint of the user attached to the tracked data.

So doesn't this mean that Plausible uses pseudonymization, which would mean that a consent banner is still needed?

Thanks

**Comment by ihucos** [comment]
Hello! Any plans how to go forward with this issue?

**Comment by metmarkosaric** [comment]
There is no legal precedent and no official way to get a "GDPR approved" certification at this point. We anonymize all datapoints and we remove the possibility of the original IP addresses being revealed in a brute-force attack. You can read more about it at https://plausible.io/data-policy. Until there is a legal precedent or official certification, we will continue to add those disclaimers like the one in our data policy that you should discuss things with your lawyer if you have some specific concerns. Will close this for now but let us know if there's anything else. We will continue monitoring the situation with the latest regulations as they happen and act accordingly. Thanks!
